### ISSUE TITLE
some question about fixed CMPG

### ISSUE THREAD

**Issue by dreamcubeblock** [ZhanHeshen/PointCMT#1]
hi, CMPG was firstly trained with a pre-trained imge encoder, should this module still be trained in the stage3? In other words, is this a shared-MLP module that can be used by both image feature and pointcloud feature? And if it is pre-trained with image feature, should we finetune it with pointcloud feature in stage 3?

**Comment by ZhanHeshen** [comment]
Hi, CMPG will NOT be trained in stage3, this is a shared module used by both image and point cloud, we usually do NOT fine-tune it in stage3.

**Comment by dreamcubeblock** [comment]
OK, Thanks for your reply!
