### ISSUE TITLE
AttributeError: 'list' object has no attribute 'to'

### ISSUE THREAD

**Issue by Kracozebr** [ZhanHeshen/PointCMT#3]
I'm trying to run your code voting_test.py
I downloaded preprocessed dataset modelnet40_test_2048pts_20views.dat
But get the error:
```
data, label = data.to(device), label.to(device).squeeze()
AttributeError: 'list' object has no attribute 'to'
```
at this line:
```
data, label = data.to(device), label.to(device).squeeze()
```
I can add the code to transform lists to tensors like this:
```
data = databatch['pointcloud']
data = torch.as_tensor(data)
label = databatch['label']
label = torch.as_tensor(label)
```
But I realized that labels are strings because it throws the error:
```
ValueError: too many dimensions 'str'
```
I can encode in labels, but I do not know how they were encoded in during training.

So what is the best way to deal with this issue?

**Comment by ZhanHeshen** [comment]
Hi Kracozebr, the label is encoded in alphabet order.

**Comment by ZhanHeshen** [comment]
You can use the following list to encode the label. Sorry for the mistake, I will update the dataset soon.

label_list = ['airplane','bathtub','bed','bench','bookshelf','bottle','bowl','car','chair','cone','cup','curtain','desk',
              'door','dresser','flower_pot','glass_box','guitar','keyboard','lamp','laptop','mantel','monitor','night_stand',
              'person','piano','plant','radio','range_hood','sink','sofa','stairs','stool','table','tent','toilet',
              'tv_stand','vase','wardrobe','xbox']
convert_name_to_label = lambda name: label_list.index(name)

**Comment by ZhanHeshen** [comment]
Hi Kracozebr, I just updated the dataset on the cloud, with changed label. Feel free to contact us if you have any problems.

**Comment by Kracozebr** [comment]
Thanks, now it works, so you could add the code in voting_test.py
```
data = torch.as_tensor(data)
label = torch.as_tensor(label)
```
Than it will work out of box.

**Comment by ZhanHeshen** [comment]
Good reminder, thank you.
