### ISSUE TITLE
CMPG模块

### ISSUE THREAD

**Issue by Littleprince2** [ZhanHeshen/PointCMT#5]
你好 @yanx27 @ZhanHeshen 
很荣幸能够学习到你的篇论文，我对你的工作非常感兴趣，在代码实现的过程中遇到一个问题向你请教：你在文章中提到CMPG模块使用的是三层MLP，而在代码中发现你只是用了一层MLP，而且我的EMD测试损失只降到了1.9，请问你在训练CMPG网络时测试损失大致降至多少？
非常谢谢！

**Comment by ZhanHeshen** [comment]
你好，我们在实验中发现一层的MLP也可以起到很好的效果，因此为了简化在代码中使用了一层。你可以按照同样的训练方式训练不用做任何修改。

**Comment by Littleprince2** [comment]
非常感谢你的回复
